apiVersion: apps/v1
kind: Deployment
metadata:
  name: potato

spec:
  selector:
    matchLabels:
      app: potato
 
  template:
    metadata:
      labels:
        app:  potato
    spec:
      containers:
      - name:  potato
        image:  leandrogelain03/potato:1.0
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: mongo-service
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongopassword
